> nextn@0.1.0 db:seed > tsx src/db/seed.ts
node:internal/modules/cjs/loader:1212
  const err = new Error(message);
              ^

Error: Cannot find module 'pg'
Require stack:
- /home/user/studio/node_modules/drizzle-orm/node-postgres/driver.cjs
- /home/user/studio/node_modules/drizzle-orm/node-postgres/index.cjs
- /home/user/studio/src/db/index.ts
- /home/user/studio/src/db/seed.ts
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at nextResolveSimple (/home/user/studio/node_modules/tsx/dist/register-D2KMMyKp.cjs:3:942)
    at /home/user/studio/node_modules/tsx/dist/register-D2KMMyKp.cjs:2:2550
    at /home/user/studio/node_modules/tsx/dist/register-D2KMMyKp.cjs:2:1624
    at resolveTsPaths (/home/user/studio/node_modules/tsx/dist/register-D2KMMyKp.cjs:3:760)
    at /home/user/studio/node_modules/tsx/dist/register-D2KMMyKp.cjs:3:1038
    at m._resolveFilename (file:///home/user/studio/node_modules/tsx/dist/register-hc1YoAqe.mjs:1:789)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/studio/node_modules/drizzle-orm/node-postgres/driver.cjs',
    '/home/user/studio/node_modules/drizzle-orm/node-postgres/index.cjs',
    '/home/user/studio/src/db/index.ts',
    '/home/user/studio/src/db/seed.ts'
  ]
}

Node.js v20.19.0